apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecab-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["list", "get", "watch"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubecab-clusterrolebinding
subjects:
- kind: User
  name: system:serviceaccount:kubecab:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubecab-clusterrole
  apiGroup: rbac.authorization.k8s.io

